# Generated by Django 5.2.7 on 2025-11-09 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livebazar', '0003_alter_costumer_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(verbose_name='Mahsulot tavsifi')),
                ('category', models.CharField(choices=[('meva', 'Meva-sabzavotlar'), ('gosht', 'Go‘sht va parranda mahsulotlari'), ('sut', 'Sut va sut mahsulotlari'), ('non', 'Non va un mahsulotlari'), ('ichimlik', 'Ichimliklar'), ('shakar', 'Shakar va shirinliklar'), ('ziravor', 'Oziq-ovqat ziravorlari'), ('uy', 'Uy-ro‘zg‘or buyumlari'), ('texnika', 'Maishiy texnika'), ('kiyim', 'Kiyim-kechak'), ('gozallik', 'Go‘zallik va parvarish vositalari'), ('qurilish', 'Qurilish mollari'), ('avto', 'Avto ehtiyot qismlar'), ('elektronika', 'Elektronika'), ('hayvon', 'Hayvonlar uchun mahsulotlar')], max_length=50, verbose_name='Kategoriya')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi (so‘mda)')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Chegirma (%)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Mavjud soni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('location', models.CharField(max_length=100, verbose_name='Joylashuv (masalan: Samarqand bozor)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Sotuvda bormi?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='livebazar.costumer')),
            ],
        ),
    ]
