# Generated by Django 5.2.7 on 2025-11-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebazar', '0002_alter_costumer_password_alter_costumer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='location',
            field=models.CharField(choices=[('toshkent', 'Toshkent'), ('fargona', "Farg'ona"), ('andijon', 'Andijon'), ('namangan', 'Namangan'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('xorazm', 'Xorazm'), ('navoiy', 'Navoiy'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo')]),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='product_category',
            field=models.CharField(choices=[('meva', 'Meva-sabzavotlar'), ('gosht', 'Go‘sht va parranda mahsulotlari'), ('sut', 'Sut va sut mahsulotlari'), ('non', 'Non va un mahsulotlari'), ('ichimlik', 'Ichimliklar'), ('shakar', 'Shakar va shirinliklar'), ('ziravor', 'Oziq-ovqat ziravorlari'), ('uy', 'Uy-ro‘zg‘or buyumlari'), ('texnika', 'Maishiy texnika'), ('kiyim', 'Kiyim-kechak'), ('gozallik', 'Go‘zallik va parvarish vositalari'), ('qurilish', 'Qurilish mollari'), ('avto', 'Avto ehtiyot qismlar'), ('elektronika', 'Elektronika'), ('hayvon', 'Hayvonlar uchun mahsulotlar')]),
        ),
    ]
